/*
* generated by Xtext
*/
package org.xtext.lrm.ui.contentassist;

import org.xtext.lrm.ui.contentassist.AbstractMultiplosdestinosProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MultiplosdestinosProposalProvider extends AbstractMultiplosdestinosProposalProvider {

}
