/*
 * generated by Xtext
 */
package org.xtext.lrm;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MultiplosdestinosRuntimeModule extends org.xtext.lrm.AbstractMultiplosdestinosRuntimeModule {

}
