/*
* generated by Xtext
*/
package org.xtext.lrm.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class MultiplosdestinosTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
