/*
* generated by Xtext
*/
package org.xtext.lrm.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MultiplosdestinosAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/lrm/parser/antlr/internal/InternalMultiplosdestinos.tokens");
	}
}
