/*
 * generated by Xtext
 */
package org.xtext.lrm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MultiplosdestinosUiModule extends org.xtext.lrm.ui.AbstractMultiplosdestinosUiModule {
	public MultiplosdestinosUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
